name: Atualizar Animação da Grade de Contribuições

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Gerar Animação da Cobrinha
      - uses: Platane/snk@master
        id: gerar-animacao-cobrinha
        with:
          github_user_name: Alxdelira
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
